remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: Paul Coral
description: Bachelor of Science in Computer Science @ EPFL, Switzerland

site:
  github:
    is_project_page: false
  
